spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauthdb
    username: root
    password: jian031018
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect